[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

# SPA用のリダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200